server:
  port: 8083

spring:
  application:
    name: login-api
  datasource:
    url: jdbc:mysql://35.198.58.59:3306/gsw_database?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: chronosapi
    password: "Bolsonaro#22"
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: none       
    open-in-view: false
    show-sql: true
  security:
    enabled: false          

app:
  jwt:
    secret: rnssz0A37Cdr7Cw89GZowLRpSWVLuOliGAC0sy+gDZzvL9Xk3OPn4fp3CZcufV75
    expiration-ms: 86400000
  cors:
    allowed-origins: "http://localhost:5173"