server:
  port: 8081

spring:
  application:
    name: ms-profissionais
  datasource:
    url: ${DB_URL:jdbc:mysql://136.117.188.200:3306/gsw_database}
    username: ${DB_USERNAME:chronosapi}
    password: ${DB_PASSWORD:Bolsonaro#22}
    driver-class-name: ${DB_DRIVER:com.mysql.cj.jdbc.Driver}
  jpa:
    hibernate:
      ddl-auto: ${JPA_DDL_AUTO:update}
    open-in-view: false
    show-sql: true

app:
  jwt:
    secret: ${JWT_SECRET:rnssz0A37Cdr7Cw89GZowLRpSWVLuOliGAC0sy+gDZzvL9Xk3OPn4fp3CZcufV75}
    expiration-ms: ${JWT_EXPIRATION_MS:86400000}
  cors:
    allowed-origins: ${APP_CORS_ALLOWED_ORIGINS:http://localhost:5173,https://*.app.github.dev}
